use_frameworks!

target 'WFURLDispatcher_Example' do
  pod 'WFURLDispatcher', :path => '../'

  target 'WFURLDispatcher_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
