use_frameworks!

target 'WFPay_Example' do
  pod 'WFPay', :path => '../'

  target 'WFPay_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
