use_frameworks!

target 'WFWebContainer_Example' do
  pod 'WFWebContainer', :path => '../'

  target 'WFWebContainer_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
