use_frameworks!

target 'WFAd_Example' do
  pod 'WFAd', :path => '../'

  target 'WFAd_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
