use_frameworks!

target 'WFCatagory_Example' do
  pod 'WFCatagory', :path => '../'

  target 'WFCatagory_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
