use_frameworks!

target 'ADSModuleMediator_Example' do
  pod 'ADSModuleMediator', :path => '../'

  target 'ADSModuleMediator_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
