use_frameworks!

target 'WFModels_Example' do
  pod 'WFModels', :path => '../'

  target 'WFModels_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
