use_frameworks!

target 'WFUIComponent_Example' do
  pod 'WFUIComponent', :path => '../'

  target 'WFUIComponent_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
