use_frameworks!

target 'WFNetwork_Example' do
  pod 'WFNetwork', :path => '../'

  target 'WFNetwork_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
