use_frameworks!

target 'WFOrder_Example' do
  pod 'WFOrder', :path => '../'

  target 'WFOrder_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
