use_frameworks!

target 'WFServiceProtocols_Example' do
  pod 'WFServiceProtocols', :path => '../'

  target 'WFServiceProtocols_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
