use_frameworks!

target 'WFDebug_Example' do
  pod 'WFDebug', :path => '../'

  target 'WFDebug_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
