use_frameworks!

target 'WFSearch_Example' do
  pod 'WFSearch', :path => '../'

  target 'WFSearch_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
