use_frameworks!

target 'WFSetting_Example' do
  pod 'WFSetting', :path => '../'

  target 'WFSetting_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
