use_frameworks!

target 'WFUser_Example' do
  pod 'WFUser', :path => '../'

  target 'WFUser_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
