use_frameworks!

target 'WFCart_Example' do
  pod 'WFCart', :path => '../'

  target 'WFCart_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
