use_frameworks!

target 'WFQRScanner_Example' do
  pod 'WFQRScanner', :path => '../'

  target 'WFQRScanner_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
